// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "./../node_modules/bs-platform/lib/es6/list.js";
import * as Random from "./../node_modules/bs-platform/lib/es6/random.js";
import * as Caml_js_exceptions from "./../node_modules/bs-platform/lib/es6/caml_js_exceptions.js";
import * as Reddit$RandomMartialMemes from "./Reddit.bs.js";

Random.init(Date.now() | 0);

function getNewPosts(param) {
  return fetch(Reddit$RandomMartialMemes.subredditURL).then((function (prim) {
                  return prim.text();
                })).then((function (text) {
                var json;
                try {
                  json = Reddit$RandomMartialMemes.parseRedditResponse(text);
                }
                catch (raw_e){
                  return Promise.reject(Caml_js_exceptions.internalToOCamlException(raw_e));
                }
                return Promise.resolve(json.data.children);
              }));
}

function getRandomRedditPost(posts) {
  return posts.then((function (posts) {
                return Promise.resolve(List.nth(posts, Random.$$int(List.length(posts))));
              }));
}

function getRandomImagePost(posts) {
  return getRandomRedditPost(posts).then((function (post) {
                var data = {
                  contents: {
                    url: "",
                    title: ""
                  }
                };
                if (!post.data.is_self && !post.data.media) {
                  data.contents = {
                    url: post.data.url,
                    title: post.data.title
                  };
                  return Promise.resolve(data);
                } else {
                  return getRandomImagePost(posts);
                }
              }));
}

export {
  getNewPosts ,
  getRandomRedditPost ,
  getRandomImagePost ,
  
}
/*  Not a pure module */
